---

- name: Remove anonymous MySQL users.
  community.mysql.mysql_user:
    name: ""
    state: absent
    login_user: root

- name: Remove MySQL test database.
  community.mysql.mysql_db:
    name: test
    state: absent
    login_user: root
